vich_uploader:
    db_driver: orm
    storage: flysystem

#    metadata:
#        type: attribute

    mappings:
        upload_images:
            #uri_prefix: /images/upload
            #upload_destination: '%kernel.project_dir%/public/images/upload'
            upload_destination: photo.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
