vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        upload_images:
            uri_prefix: /images/upload
            upload_destination: '%kernel.project_dir%/public/images/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
